### ISSUE TITLE
Resolve documentation better

### ISSUE THREAD

**Issue by fnielsen** [structureddynamics/Bibliographic-Ontology-BIBO#10]
I would be nice with human readable specification without protege.

http://purl.org/ontology/bibo/pmid does not resolve to a human readable documentation.

Old documentation exists at https://web.archive.org/web/20100725183526/http://bibotools.googlecode.com/svn/bibo-ontology/trunk/doc/index.html This does not resolve https://web.archive.org/web/20100725183526/http://bibotools.googlecode.com/svn/bibo-ontology/trunk/doc/index.html

http://bibliontology.com/ or http://bibliographic-ontology.org/ has not human readable specification.

The link to https://raw.github.com/structureddynamics/Bibliographic-Ontology-BIBO/ma... at the bottom is wrong.

The link on http://bibliographic-ontology.org/ is also wrong. The file has two extensions.

Nothing seems to be available here https://code.google.com/archive/p/bibotools/source

The links on http://bibliontology.com/changelog.html on this page does not work.

**Comment by corined** [comment]
I agree. I don't have Protege. I used to access the human readable ontology from the latest version available at the changelog page. This now returns a 404. Thanks for looking into this.

**Comment by fgiasson** [comment]
Hi @fnielsen,

> I would be nice with human readable specification without protege.

I agree, but I will have to check what is the current state of ontologies documentation generator (in HTML). I may have to write one myself since last time I looked into this everything was pretty much deprecated. Shouldn't be too much of an effort, but still time to put in that.

> http://purl.org/ontology/bibo/pmid does not resolve to a human readable documentation.

Here we really have an issue. In fact, two concurrent issues:

1. We lost the bibliontology.com domain. This is why everything is now under bibliographic-ontology.org.
2. The biggest problem is that purl.org is unmaintained and basically dead. [Here is the discussion about that issue](https://groups.google.com/forum/#!topic/persistenturls/Zpd4BHQxxIM).

Right now, I am thinking about what we could do since all the BIBO URIs are not dereferencable anymore. This also affect other major ontologies such as the Music Ontology (MO).

Otherwise I agree, the complete BIBO's website should be re-created, or at least updated, probably around a new human readable specification. This one site is quite old, and deprecated since it uses Drupal 6.

**Comment by fgiasson** [comment]
Some news about that. First, bibliontology.com appears to be back operational. I fixed the script that was delivering the ontology's description using content negotiation.

I also fixed the links from the website to the new URL in Github.

I also got an outreach from a developer of the GS1 vocabulary and we may endup using a version of their system to create human readable documentation for BIBO which would replace the current (8 years old!) website.

I will keep you posted on that regard, it may happen somewhere in October depending on its availabilities.

**Comment by jentschk** [comment]
Hi @fgiasson ,
could you have another look at the Github link in sec http://bibliontology.com/#sec-documentation?
Many thanks!

**Comment by fgiasson** [comment]
@jentschk the issue is that you are not using the proper domain name. We had an issue with that one and we lost it so the new domain is: http://bibliographic-ontology.org

Also bibliontology.com got aquired by an unknown party that apparently cloned the site. However, I don't have access to that server. It is why the sec-documentation section is still problematic. 

To make things even more confusing, purl.org was not working anymore so I couldn't redirect perl to the new server.

However, as of 2 days ago, Purl is now managed by the web archive, which is a really great news.

All this being said, bibliontology.com should never be used again, and the new domain is bibliographic-ontology.org. All the references to bibliontology.com should be fixed (github.com + purl.org).
