### ISSUE TITLE
bibo:abstract

### ISSUE THREAD

**Issue by jentschk** [structureddynamics/Bibliographic-Ontology-BIBO#8]
Hi,

some colleagues and I were looking at 'bibo:abstract' and wondered if it is meant to be a separate bibo property or was actually meant to be a reference to 'dcterms:abstract'. That is because 'rdfs:isDefinedBy' points to 'http://purl.org/dc/terms/'.

Thanks,
Jana

**Comment by fgiasson** [comment]
Hi @jentschk,

I think that historically it was meant to be a `BIBO` property. In this case, the isDefinedBy would be a mistake. I will have to check when we introduced and see if it changed over time. If the error is the other way around, then we won't have choice to keep it and mark it as deprecated since many people are probably using it with the `BIBO` namespace.

I will look into this a bit later.

Thanks for reporting!
